name: Pull Request
on: [push]

jobs:
  start-job:
    name: Start Job
    runs-on: ubuntu-latest
    steps:
      - name: Start Job.
        run: echo "PR created. Builds will be triggered here for forked PRs or Buildkite for internal PRs."


  amazon_linux-2-build:
    # if: github.event.pull_request.base.repo.id != github.event.pull_request.head.repo.id
    name: Amazon_Linux 2 | Build
    runs-on: ubuntu-latest
    needs: start-job
    steps:
      - name: Checkout
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e
        with:
          submodules: recursive
      - name: Build
        run: | 
          ./.cicd/build.sh
          tar -pczf build.tar.gz build
        env:
          IMAGE_TAG: amazonlinux-2
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v1
        with:
          name: amazon_linux-2-build
          path: build.tar.gz
  amazon_linux-2-unit-test:
    name: Amazon_Linux 2 | Unit Test
    runs-on: ubuntu-latest
    needs: amazon_linux-2-build
    steps:
      - name: Checkout
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e
        with:
          submodules: recursive
      - name: Download Build Artifact
        uses: actions/download-artifact@v1
        with:
          name: amazon_linux-2-build
      - name: Unit Test
        run: | 
          tar -xzf amazon_linux-2-build/build.tar.gz
          ./.cicd/test.sh
        env:
          IMAGE_TAG: amazonlinux-2
  amazon_linux-2-toolchain-test:
    name: Amazon_Linux 2 | Toolchain Test
    runs-on: ubuntu-latest
    needs: amazon_linux-2-build
    steps:
      - name: Checkout
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e
        with:
          submodules: recursive
      - name: Download Build Artifact
        uses: actions/download-artifact@v1
        with:
          name: amazon_linux-2-build
      - name: Toolchain Test
        run: | 
          tar -xzf amazon_linux-2-build/build.tar.gz
          ./.cicd/toolchain-tests.sh
        env:
          IMAGE_TAG: amazonlinux-2


  centos-77-build:
    # if: github.event.pull_request.base.repo.id != github.event.pull_request.head.repo.id
    name: CentOS 7.7 | Build
    runs-on: ubuntu-latest
    needs: start-job
    steps:
      - name: Checkout
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e
        with:
          submodules: recursive
      - name: Build
        run: | 
          ./.cicd/build.sh
          tar -pczf build.tar.gz build
        env:
          IMAGE_TAG: centos-7.7
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v1
        with:
          name: centos-77-build
          path: build.tar.gz
  centos-77-unit-test:
    name: CentOS 7.7 | Unit Test
    runs-on: ubuntu-latest
    needs: centos-77-build
    steps:
      - name: Checkout
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e
        with:
          submodules: recursive
      - name: Download Build Artifact
        uses: actions/download-artifact@v1
        with:
          name: centos-77-build
      - name: Unit Test
        run: | 
          tar -xzf centos-77-build/build.tar.gz
          ./.cicd/test.sh
        env:
          IMAGE_TAG: centos-7.7
  centos-77-toolchain-test:
    name: CentOS 7.7 | Toolchain Test
    runs-on: ubuntu-latest
    needs: centos-77-build
    steps:
      - name: Checkout
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e
        with:
          submodules: recursive
      - name: Download Build Artifact
        uses: actions/download-artifact@v1
        with:
          name: centos-77-build
      - name: Toolchain Test
        run: | 
          tar -xzf centos-77-build/build.tar.gz
          ./.cicd/toolchain-tests.sh
        env:
          IMAGE_TAG: centos-7.7


  ubuntu-1604-build:
    # if: github.event.pull_request.base.repo.id != github.event.pull_request.head.repo.id  
    name: Ubuntu 16.04 | Build
    runs-on: ubuntu-latest
    needs: start-job
    steps:
      - name: Checkout
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e
        with:
          submodules: recursive
      - name: Build
        run: | 
          ./.cicd/build.sh
          tar -pczf build.tar.gz build
        env:
          IMAGE_TAG: ubuntu-16.04
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ubuntu-1604-build
          path: build.tar.gz
  ubuntu-1604-unit-test:
    name: Ubuntu 16.04 | Unit Test
    runs-on: ubuntu-latest
    needs: ubuntu-1604-build
    steps:
      - name: Checkout
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e
        with:
          submodules: recursive
      - name: Download Build Artifact
        uses: actions/download-artifact@v1
        with:
          name: ubuntu-1604-build
      - name: Unit Test
        run: | 
          tar -xzf ubuntu-1604-build/build.tar.gz
          ./.cicd/test.sh
        env:
          IMAGE_TAG: ubuntu-16.04
  ubuntu-1604-toolchain-test:
    name: Ubuntu 16.04 | Toolchain Test
    runs-on: ubuntu-latest
    needs: ubuntu-1604-build
    steps:
      - name: Checkout
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e
        with:
          submodules: recursive
      - name: Download Build Artifact
        uses: actions/download-artifact@v1
        with:
          name: ubuntu-1604-build
      - name: Toolchain Test
        run: | 
          tar -xzf ubuntu-1604-build/build.tar.gz
          ./.cicd/toolchain-tests.sh
        env:
          IMAGE_TAG: ubuntu-16.04


  ubuntu-1804-build:
    # if: github.event.pull_request.base.repo.id != github.event.pull_request.head.repo.id
    name: Ubuntu 18.04 | Build
    runs-on: ubuntu-latest
    needs: start-job
    steps:
      - name: Checkout
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e
        with:
          submodules: recursive
      - name: Build
        run: | 
          ./.cicd/build.sh
          tar -pczf build.tar.gz build
        env:
          IMAGE_TAG: ubuntu-18.04
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ubuntu-1804-build
          path: build.tar.gz
  ubuntu-1804-unit-test:
    name: Ubuntu 18.04 | Unit Test
    runs-on: ubuntu-latest
    needs: ubuntu-1804-build
    steps:
      - name: Checkout
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e
        with:
          submodules: recursive
      - name: Download Build Artifact
        uses: actions/download-artifact@v1
        with:
          name: ubuntu-1804-build
      - name: Unit Test
        run: | 
          tar -xzf ubuntu-1804-build/build.tar.gz
          ./.cicd/test.sh
        env:
          IMAGE_TAG: ubuntu-18.04
  ubuntu-1804-toolchain-test:
    name: Ubuntu 18.04 | Toolchain Test
    runs-on: ubuntu-latest
    needs: ubuntu-1804-build
    steps:
      - name: Checkout
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e
        with:
          submodules: recursive
      - name: Download Build Artifact
        uses: actions/download-artifact@v1
        with:
          name: ubuntu-1804-build
      - name: Toolchain Test
        run: | 
          tar -xzf ubuntu-1804-build/build.tar.gz
          ./.cicd/toolchain-tests.sh
        env:
          IMAGE_TAG: ubuntu-18.04


  macos-1015-build:
    # if: github.event.pull_request.base.repo.id != github.event.pull_request.head.repo.id
    name: MacOS 10.15 | Build
    runs-on: macos-latest
    needs: start-job
    steps:
      - name: Checkout
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e
        with:
          submodules: recursive
      - name: Build
        run: | 
          brew install git automake libtool wget cmake gmp gettext doxygen graphviz lcov python@3
          ./.cicd/build.sh
          tar -pczf build.tar.gz build
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v1
        with:
          name: macos-1015-build
          path: build.tar.gz
  macos-1015-unit-test:
    name: MacOS 10.15 | Unit Test
    runs-on: macos-latest
    needs: amazon_linux-2-build
    steps:
      - name: Checkout
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e
        with:
          submodules: recursive
      - name: Download Build Artifact
        uses: actions/download-artifact@v1
        with:
          name: macos-1015-build
      - name: Unit Test
        run: | 
          brew install git automake libtool wget cmake gmp gettext doxygen graphviz lcov python@3
          tar -xzf macos-1015-build/build.tar.gz
          ./.cicd/test.sh
  macos-1015-toolchain-test:
    name: MacOS 10.15 | Toolchain Test
    runs-on: macos-latest
    needs: macos-1015-build
    steps:
      - name: Checkout
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e
        with:
          submodules: recursive
      - name: Download Build Artifact
        uses: actions/download-artifact@v1
        with:
          name: macos-1015-build
      - name: Toolchain Test
        run: | 
          brew install git automake libtool wget cmake gmp gettext doxygen graphviz lcov python@3
          tar -xzf macos-1015-build/build.tar.gz
          ./.cicd/toolchain-tests.sh
